spring:
  main:
    banner-mode: "off"
  data:
    mongodb:
      uri: mongodb+srv://admin-user:Adm1n636@mflix-wwebc.mongodb.net/test?maxPoolSize=10&w=majority&wtimeoutMS=2500&connectTimeoutMS=2000
      database: icw_directory

server:
  port: ${PORT:8080}

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    pathsToMatch: "/directory/*"
