name: Main workflow

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Compile and Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Build code
        run: mvn clean compile -B -V
      - name: Test with Maven
        run: mvn test -B -V

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_MAIL}}
          healthcheck: "https://${{secrets.HEROKU_APP}}.herokuapp.com/actuator/health"
          delay: 30
        env:
          HD_SPRING_DATA_MONGODB_URI: ${{secrets.DB_URI}}
          HD_SPRING_DATA_MONGODB_DATABASE: ${{secrets.DB_NAME}}